// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat.post').default>>>>
    }
    '/api/enable-login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/enable-login').default>>>>
    }
    '/api/latest': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/latest').default>>>>
    }
    '/api/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/login').default>>>>
    }
    '/api/mcp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/mcp.post').default>>>>
    }
    '/api/me': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/me/index').default>>>>
    }
    '/api/me/sync': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/me/sync').default>>>>
    }
    '/api/oauth/github': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/oauth/github').default>>>>
    }
    '/api/projects/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/projects/[id]').default>>>>
    }
    '/api/projects': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/projects/index').default>>>>
    }
    '/api/s/entire': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/s/entire.post').default>>>>
    }
    '/api/s': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/s/index').default>>>>
    }
  }
}
export {}